name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "Running tests..."
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t <your-dockerhub-username>/todo-app:latest .
          docker push <your-dockerhub-username>/todo-app:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Sao chép setup-docker.sh từ repository
            echo "Copying setup-docker.sh to EC2..."
            cat setup-docker.sh > /home/ec2-user/setup-docker.sh
            # Cấp quyền thực thi
            chmod +x /home/ec2-user/setup-docker.sh
            # Chạy script với sudo
            sudo /home/ec2-user/setup-docker.sh || true
            # Đảm bảo Docker đang chạy
            sudo systemctl start docker
            sudo systemctl enable docker
            # Kéo và chạy container
            docker pull <your-dockerhub-username>/todo-app:latest
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d --name todo-app -p 5000:5000 <your-dockerhub-username>/todo-app:latest